# Generated by Django 2.1.2 on 2018-11-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=29),
        ),
    ]
