# Generated by Django 2.1.2 on 2018-11-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Class',
        ),
    ]
