# Generated by Django 2.1.2 on 2018-11-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20181102_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32, null=True)),
                ('cid', models.IntegerField(null=True)),
            ],
        ),
    ]
