# Generated by Django 2.1.2 on 2018-11-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_student2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student2',
            table='Student',
        ),
    ]
