# Generated by Django 2.1.2 on 2018-11-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20181102_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='cid',
            field=models.IntegerField(null=True),
        ),
    ]
