# Generated by Django 2.1.2 on 2018-11-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_class2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class2',
            table='Class2',
        ),
    ]
