# Generated by Django 2.1.2 on 2018-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20181104_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32, null=True)),
                ('cid', models.IntegerField(null=True)),
            ],
        ),
    ]
