# Generated by Django 2.1.2 on 2018-11-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_student1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student1',
            table='Student2',
        ),
    ]
