# Generated by Django 2.1.2 on 2018-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_auto_20181104_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=None, to='app01.Class2'),
            preserve_default=False,
        ),
    ]
