# Generated by Django 2.1.2 on 2018-11-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20181105_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class0',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('first_day', models.DateField()),
            ],
        ),
    ]
