# Generated by Django 2.1.2 on 2018-11-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_class0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student0',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Class0')),
            ],
        ),
    ]
