# Generated by Django 2.1.2 on 2018-11-07 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_student0'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student0',
            name='detall',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.StudentDetall'),
        ),
    ]
