# Generated by Django 2.1.2 on 2018-11-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_auto_20181107_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student0',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app01.Class0'),
        ),
    ]
